title: Harjeet Singh
logo: /harjeet.png
description: Transforming workflows with scalable, automated build structure | Build and Deploy Engineer at Medavie Bluecross
#show_downloads: true
theme: jekyll-theme-minimal
